from __future__ import annotations

import re

TYPO_REPLACEMENTS = {
    "kiero": "quiero",
    "qiero": "quiero",
    "keremos": "queremos",
    "qeremos": "queremos",
    "gustaria": "me gustaria",
    "vehiculo": "vehiculo",
    "dificil": "dificil",
    "ninos": "ninos",
}

FOOD_TERMS = (
    "comer",
    "comida",
    "restaurant",
    "restaurante",
    "pizza",
    "pizzería",
    "pizzeria",
    "café",
    "cafe",
    "gastronomía",
    "gastronomia",
    "almorzar",
    "cenar",
    "sopa",
    "sopas",
    "sopitas",
    "sopias",
    "carne",
    "carnes",
    "cazuela",
    "económico",
    "economico",
    "picada",
    "picadas",
)
SPECIFIC_FOOD_TERMS = (
    "pizza",
    "pizzería",
    "pizzeria",
    "café",
    "cafe",
    "sushi",
    "hamburguesa",
    "pastelería",
    "pasteleria",
    "mariscos",
    "marisco",
    "comida local",
    "sopa",
    "sopas",
    "sopias",
    "carne",
    "carnes",
    "cazuela",
)
FOOD_COMPLETION_TAGS = {"pizza", "cafe", "comida_local", "artesanal", "rapido"}
NATURE_TERMS = (
    "naturaleza",
    "sendero",
    "trekking",
    "mirador",
    "lago",
    "volcán",
    "volcan",
    "playa",
    "parque",
    "cascada",
    "terma",
    "outdoor",
    "aire libre",
)
CULTURE_TERMS = ("museo", "cultura", "historia", "mapuche", "artesanía", "artesania", "feria")
REST_TERMS = ("descansar", "relajo", "relajar", "termas", "spa", "bienestar", "tranquilo", "tranquila")
ADVENTURE_TERMS = ("aventura", "rafting", "kayak", "canopy", "bicicleta", "mtb", "esquí", "esqui")
LODGING_TERMS = ("alojamiento", "hotel", "hostal", "hostel", "cabaña", "cabana", "dormir", "hospedaje", "camping")
GENERATE_TERMS = (
    "haz el itinerario",
    "hacer el itinerario",
    "crear itinerario",
    "crea itinerario",
    "crea el itinerario",
    "crear itinerario con lo acordado",
    "itinerario con lo acordado",
    "arma la ruta",
    "armame la ruta",
    "genera el itinerario",
    "generar itinerario",
    "genera la ruta",
    "generar la ruta",
    "haz la ruta",
    "planificalo",
    "listo genera",
    "con lo que ya te di",
    "hazlo con lo que tenemos",
    "con lo que tenemos",
    "con lo acordado",
)
SURPRISE_ROUTE_TERMS = (
    "hazlo todo",
    "hazlo tu",
    "hazlo tú",
    "ruta sorpresa",
    "ruta equilibrada",
    "haz una ruta sorpresa",
    "haz una ruta sorpresa equilibrada",
    "haz una ruta sorpresa equilibrada y completa",
    "haz una ruta sorpresa equilibrada y completa con alojamiento, comidas y actividades",
    "arma todo",
    "decide tu",
    "decide tú",
)
RESET_TERMS = (
    "olvida eso",
    "olvidemos eso",
    "nuevo plan",
    "nuevo viaje",
    "empecemos de nuevo",
    "partamos de nuevo",
    "cambiemos el plan",
    "cambiar totalmente",
    "otra cosa",
    "algo totalmente distinto",
)
SHOW_OPTIONS_TERMS = ("muestrame opciones", "muéstrame opciones", "ver opciones", "que opciones", "qué opciones")
REFINEMENT_TERMS = (
    "quiero",
    "prefiero",
    "busco",
    "me gustaria",
    "me gustaría",
    "ponle",
    "agregale",
    "agrégale",
    "prioriza",
    "dejalo",
    "déjalo",
    "hazlo mas",
    "hazlo más",
    "necesito una ruta",
    "me tinca",
    "vamos con",
    "sumar",
    "suma",
    "agrega",
    "agregar",
)
SKIP_DAY_TERMS = (
    "pasemos al",
    "siguiente dia",
    "siguiente día",
    "avancemos al",
    "pasemos al siguiente",
    "avanzar al",
    "saltar al",
    "saltemos al",
    "ya siguiente",
    "siguiente",
    "proximo dia",
    "próximo día",
)
FOCUS_DAY_TERMS = (
    "volvamos al",
    "cambiemos al",
    "quiero planificar el dia",
    "quiero planificar el día",
    "el lunes",
    "el martes",
    "el miercoles",
    "el miércoles",
    "el jueves",
    "el viernes",
    "el sabado",
    "el sábado",
    "el domingo",
    "dia 1",
    "dia 2",
    "dia 3",
    "dia 4",
    "dia 5",
    "dia 6",
    "dia 7",
    "día 1",
    "día 2",
    "día 3",
    "día 4",
    "día 5",
    "día 6",
    "día 7",
)
LODGING_REQUEST_TERMS = (
    "buscar alojamiento",
    "donde dormir",
    "dónde dormir",
    "buscar hotel",
    "ver hoteles",
    "ver cabanas",
    "ver cabañas",
    "quiero alojarme",
    "donde alojarme",
    "dónde alojarme",
    "donde quedarme",
    "dónde quedarme",
    "busco alojamiento",
    "busco hotel",
    "busco cabana",
    "busco cabaña",
    "alojamiento",
    "hospedaje",
)
LODGING_MODE_TERMS = (
    "todos los dias",
    "todos los días",
    "todo el finde",
    "todo el fin de semana",
    "el finde completo",
    "solo el viernes",
    "solo el sabado",
    "solo el sábado",
    "solo el domingo",
    "solo el lunes",
    "solo el martes",
    "solo el miercoles",
    "solo el miércoles",
    "solo el jueves",
    "el finde nomas",
    "el finde nomás",
    "los tres dias",
    "los tres días",
    "los dos dias",
    "los dos días",
)
FREE_QUESTION_TERMS = (
    "auto",
    "vehiculo",
    "vehículo",
    "bici",
    "caminando",
    "caminar",
    "lejos",
    "distancia",
    "precio",
    "entrada",
    "ticket",
    "horario",
    "abierto",
    "cerrado",
    "clima",
    "lluvia",
    "frio",
    "frío",
    "calor",
    "niños",
    "ninos",
    "familia",
    "adulto mayor",
    "dificultad",
    "dificil",
    "difícil",
    "facil",
    "fácil",
    "peligroso",
    "seguro",
    "estacionamiento",
    "baño",
    "bano",
    "acceso",
    "camino",
    "ripio",
    "que significa",
    "qué significa",
    "a que te refieres",
    "a qué te refieres",
    "se puede",
    "conviene",
    "sirve",
)

LOCATION_PATTERN = re.compile(r"\b(?:en|a|por|cerca de)\s+([A-ZÁÉÍÓÚÑ][\wáéíóúñÁÉÍÓÚÑ-]+(?:\s+[A-ZÁÉÍÓÚÑ][\wáéíóúñÁÉÍÓÚÑ-]+)?)")
UUID_PATTERN = re.compile(r"[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}")
ITINERARY_ID_PATTERN = re.compile(r"itinerary[_\s-]*id\s*[:=]?\s*(?P<id>[0-9a-fA-F-]{36})", re.IGNORECASE)
STEP_ID_PATTERN = re.compile(r"step[_\s-]*id\s*[:=]?\s*(?P<id>[0-9a-fA-F-]{36})", re.IGNORECASE)
USE_POI_PATTERN = re.compile(
    r"usar\s+poi\s+(?P<poi_id>[0-9a-fA-F-]{36})(?:\s+para\s+step\s+(?P<step_id>[0-9a-fA-F-]{36}))?",
    re.IGNORECASE,
)
SELECT_POI_PATTERN = re.compile(
    r"(?:seleccionar|elegir|usar|quiero ir a)\s+poi\s+(?P<poi_id>[0-9a-fA-F-]{36})",
    re.IGNORECASE,
)

WEEKDAY_NAMES = {
    0: "lunes",
    1: "martes",
    2: "miércoles",
    3: "jueves",
    4: "viernes",
    5: "sábado",
    6: "domingo",
}
WEEKDAY_ALIASES = {
    "lunes": 0,
    "martes": 1,
    "miercoles": 2,
    "miércoles": 2,
    "jueves": 3,
    "viernes": 4,
    "sabado": 5,
    "sábado": 5,
    "domingo": 6,
}
DAY_ORDINAL_ALIASES = {
    "primer dia": 1,
    "primer día": 1,
    "dia 1": 1,
    "día 1": 1,
    "segundo dia": 2,
    "segundo día": 2,
    "dia 2": 2,
    "día 2": 2,
    "tercer dia": 3,
    "tercer día": 3,
    "dia 3": 3,
    "día 3": 3,
    "cuarto dia": 4,
    "cuarto día": 4,
    "dia 4": 4,
    "día 4": 4,
    "quinto dia": 5,
    "quinto día": 5,
    "dia 5": 5,
    "día 5": 5,
    "sexto dia": 6,
    "sexto día": 6,
    "dia 6": 6,
    "día 6": 6,
    "septimo dia": 7,
    "séptimo día": 7,
    "dia 7": 7,
    "día 7": 7,
}

GASTRONOMY_CATEGORY_IDS = {2}
LODGING_CATEGORY_IDS = {4}
NATURE_CATEGORY_IDS = {1, 6, 7, 8, 9, 10, 12}
CULTURE_CATEGORY_IDS = {5, 11, 15}

GASTRONOMY_TEXT_TERMS = {
    "restaurant",
    "restaurante",
    "pizzeria",
    "pizzería",
    "pizza",
    "cafe",
    "café",
    "comida",
    "cocina",
    "bar",
    "pub",
    "empanada",
    "sushi",
    "marisco",
    "sopa",
    "sopas",
    "cazuela",
    "carne",
    "carnes",
    "picada",
    "pasteleria",
    "pastelería",
}
LODGING_TEXT_TERMS = {"hotel", "hostal", "hostel", "cabaña", "cabana", "alojamiento", "hospedaje", "camping"}
NATURE_TEXT_TERMS = {"sendero", "trekking", "mirador", "lago", "volcan", "volcán", "parque", "cascada", "terma"}
CULTURE_TEXT_TERMS = {"museo", "patrimonio", "mapuche", "artesania", "artesanía", "historia", "feria"}

KNOWN_DESTINATION_CENTERS: dict[str, tuple[float, float]] = {
    "Pucón": (-39.2820, -71.9545),
    "Villarrica": (-39.2857, -72.2279),
    "Lican Ray": (-39.4889, -72.1558),
    "Caburgua": (-39.1669, -71.7817),
    "Curarrehue": (-39.3581, -71.5887),
    "Temuco": (-38.7359, -72.5904),
    "Melipeuco": (-38.8519, -71.6913),
    "Parque Nacional Conguillío": (-38.6500, -71.6500),
    "Malalcahuello": (-38.4702, -71.5700),
    "Lonquimay": (-38.4333, -71.2333),
    "Angol": (-37.7952, -72.7164),
    "Freire": (-38.9525, -72.6265),
    "Padre Las Casas": (-38.7667, -72.6000),
    "Nueva Imperial": (-38.7445, -72.9507),
    "Carahue": (-38.7118, -73.1610),
    "Saavedra": (-38.7833, -73.4000),
    "Puerto Saavedra": (-38.7833, -73.4000),
    "Teodoro Schmidt": (-38.9961, -73.0892),
    "Toltén": (-39.2167, -73.2167),
    "Gorbea": (-39.1010, -72.6741),
    "Pitrufquén": (-38.9864, -72.6372),
    "Loncoche": (-39.3671, -72.6303),
    "Lautaro": (-38.5307, -72.4365),
    "Perquenco": (-38.4167, -72.3833),
    "Galvarino": (-38.4088, -72.7827),
    "Cholchol": (-38.6018, -72.8457),
    "Vilcún": (-38.6689, -72.2244),
    "Cunco": (-38.9329, -72.0270),
    "Curacautín": (-38.4390, -71.8891),
    "Victoria": (-38.2329, -72.3329),
    "Traiguén": (-38.2500, -72.6833),
    "Lumaco": (-38.1500, -72.9167),
    "Purén": (-38.0314, -73.0711),
    "Renaico": (-37.6727, -72.5888),
    "Ercilla": (-38.0583, -72.3769),
    "Collipulli": (-37.9545, -72.4344),
    "Los Sauces": (-37.9776, -72.8353),
    "Región de La Araucanía": (-38.7400, -72.1000),
}
KNOWN_DESTINATION_NAMES = (
    "pucon",
    "pucón",
    "villarrica",
    "lican ray",
    "licán ray",
    "caburgua",
    "curarrehue",
    "temuco",
    "melipeuco",
    "conguillio",
    "conguillío",
    "malalcahuello",
    "lonquimay",
    "angol",
    "santiago",
    "freire",
    "padre las casas",
    "nueva imperial",
    "carahue",
    "saavedra",
    "puerto saavedra",
    "teodoro schmidt",
    "toltén",
    "tolten",
    "gorbea",
    "pitrufquén",
    "pitrufquen",
    "loncoche",
    "lautaro",
    "perquenco",
    "galvarino",
    "cholchol",
    "vilcún",
    "vilcun",
    "cunco",
    "curacautín",
    "curacautin",
    "victoria",
    "traiguén",
    "traiguen",
    "lumaco",
    "purén",
    "puren",
    "renaico",
    "ercilla",
    "collipulli",
    "los sauces",
    "curarrehue",
    "araucania",
    "araucanía",
)

STRICT_DESTINATION_SOURCES = {
    "detected_destination",
    "detected_destination_group",
    "geocoded_destination",
    "inherited_destination",
}
EXPAND_DESTINATION_TERMS = (
    "ampliar",
    "amplia",
    "amplía",
    "alrededores",
    "cerca de",
    "comunas cercanas",
    "zonas cercanas",
    "me puedo mover",
    "puedo moverme",
    "no importa moverme",
    "fuera de",
)
LOCAL_RESULT_WARNING_THRESHOLD = 3
MIN_ITINERARY_CONTEXT_POIS = 5

DESTINATION_REQUEST_PATTERN = re.compile(
    r"\b(?:voy|vamos|viajo|viajar|ir|iremos|quedarme|alojarme|estar[eé]?|estoy)\s+(?:a|en)\s+"
)
SERVICE_IN_LOCATION_PATTERN = re.compile(
    r"\b(?:restaurantes?|hoteles?|hostales?|alojamientos?|lugares|panoramas|comida|caf[eé]s?)\s+en\s+"
)

DESTINATION_DISPLAY_NAMES = {
    "pucon": "Pucón",
    "villarrica": "Villarrica",
    "lican ray": "Lican Ray",
    "caburgua": "Caburgua",
    "curarrehue": "Curarrehue",
    "temuco": "Temuco",
    "melipeuco": "Melipeuco",
    "conguillio": "Parque Nacional Conguillío",
    "malalcahuello": "Malalcahuello",
    "lonquimay": "Lonquimay",
    "angol": "Angol",
    "santiago": "Santiago",
    "freire": "Freire",
    "padre las casas": "Padre Las Casas",
    "nueva imperial": "Nueva Imperial",
    "carahue": "Carahue",
    "saavedra": "Saavedra",
    "puerto saavedra": "Puerto Saavedra",
    "teodoro schmidt": "Teodoro Schmidt",
    "tolten": "Toltén",
    "gorbea": "Gorbea",
    "pitrufquen": "Pitrufquén",
    "loncoche": "Loncoche",
    "lautaro": "Lautaro",
    "perquenco": "Perquenco",
    "galvarino": "Galvarino",
    "cholchol": "Cholchol",
    "vilcun": "Vilcún",
    "cunco": "Cunco",
    "curacautin": "Curacautín",
    "victoria": "Victoria",
    "traiguen": "Traiguén",
    "lumaco": "Lumaco",
    "puren": "Purén",
    "renaico": "Renaico",
    "ercilla": "Ercilla",
    "collipulli": "Collipulli",
    "los sauces": "Los Sauces",
    "araucania": "Región de La Araucanía",
}
